name: Build and Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'frontend/**'
      - 'k8s/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      image_owner: ${{ steps.login.outputs.username }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.login.outputs.username }}/mlops-api
            ghcr.io/${{ steps.login.outputs.username }}/mlops-frontend
          tags: |
            type=sha,prefix=

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ghcr.io/${{ steps.login.outputs.username }}/mlops-api

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ghcr.io/${{ steps.login.outputs.username }}/mlops-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Kubernetes manifests with new image tag
        run: |
          IMAGE_OWNER=$(echo "${{ needs.build-and-push.outputs.image_owner }}" | tr '[:upper:]' '[:lower:]')
          sed -i "s|image: .*mlops-api:.*|image: ghcr.io/$IMAGE_OWNER/mlops-api:${{ needs.build-and-push.outputs.image_tag }}|" k8s/api-deployment.yml
          sed -i "s|image: .*mlops-frontend:.*|image: ghcr.io/$IMAGE_OWNER/mlops-frontend:${{ needs.build-and-push.outputs.image_tag }}|" k8s/frontend-deployment.yml
          echo "Manifests updated."
          cat k8s/api-deployment.yml
          cat k8s/frontend-deployment.yml

      - name: Instructions for manual deployment
        run: |
          echo "Workflow complete. New images have been pushed to GHCR."
          echo "To deploy the new version to your local Docker Desktop Kubernetes, run the following command on your local machine:"
          echo "kubectl apply -f k8s/"