name: Build and Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'frontend/**'
      - 'k8s/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.vars.outputs.sha_short }}
      image_owner: ${{ steps.vars.outputs.owner_lowercase }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set reusable variables
        id: vars
        run: |
          owner_lowercase=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lowercase=$owner_lowercase" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner_lowercase }}/mlops-api:${{ steps.vars.outputs.sha_short }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner_lowercase }}/mlops-frontend:${{ steps.vars.outputs.sha_short }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Kubernetes manifests with new image tag
        run: |
          sed -i "s|image: .*mlops-api:.*|image: ghcr.io/${{ needs.build-and-push.outputs.image_owner }}/mlops-api:${{ needs.build-and-push.outputs.image_tag }}|" k8s/api-deployment.yml
          sed -i "s|image: .*mlops-frontend:.*|image: ghcr.io/${{ needs.build-and-push.outputs.image_owner }}/mlops-frontend:${{ needs.build-and-push.outputs.image_tag }}|" k8s/frontend-deployment.yml
          echo "Manifests updated."
          cat k8s/api-deployment.yml
          cat k8s/frontend-deployment.yml

      - name: Instructions for manual deployment
        run: |
          echo "Workflow complete. New images have been pushed to GHCR."
          echo "To deploy the new version to your local Docker Desktop Kubernetes, run the following command on your local machine:"
          echo "kubectl apply -f k8s/"